name: CI/CD Pipeline for Sentiment Analysis Model

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Train Model
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run training script
      - name: Run sentiment training script
        run: |
          python sentiment_ml_pipeline.py

      # Step 5: Upload trained model and vectorizer
      - name: Upload trained model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sentiment-model-artifacts
          path: |
            sentiment_model.pkl
            tfidf_vectorizer.pkl

  deploy:
    name: Deploy Model
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Simulate deployment
        run: |
          echo "Deploying trained model to cloud/server..."
          # Add your actual deployment logic here (e.g., SCP, AWS CLI, GCP CLI)
